#!/bin/bash

# Validate argument
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <logfile>"
    exit 1
fi

logfile="$1"

if [ ! -f "$logfile" ]
then
    echo "Error: Invalid file."
    exit 1
fi

if [ ! -r "$logfile" ]
then
        echo "Error : File is not readble"
        exit 1
fi

# Output file
output_file="summary.txt"

# Basic counts
total_lines=$(wc -l < "$logfile")
error_count=$(grep -i -c "error" "$logfile")
warning_count=$(grep -i -c "warning" "$logfile")

# Top 3 meaningful words


# structured summary
cat <<EOF > "$output_file"
========================================
            LOG SUMMARY REPORT
========================================

Input File        : $logfile
Generated On      : $(date '+%Y-%m-%d %H:%M:%S')
Generated By      : $(basename "$0")

----------------------------------------
BASIC STATISTICS
----------------------------------------
Total Lines      : $total_lines
ERROR Count      : $error_count
WARNING Count    : $warning_count

----------------------------------------
TOP 3 FREQUENT WORDS
----------------------------------------

----------------------------------------
END OF REPORT 
----------------------------------------

EOF

echo "Summary generated successfully → $output_file"

